# Site settings
title: victcity
email: victcity@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  victcity's blog
baseurl:  # the subpath of your site, e.g. /blog/
url:  "http://victcity.github.io/" # the base hostname & protocol for your site
#twitter_username: twitter_username
github_username:  victcity

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
